/**
 * tests/tool-schema-dump.test.ts — the published tool surface must stay honest.
 *
 * THE FAILURE THIS PREVENTS. An embedding host pinned its build specification to
 * daemon version 0.2.6 and planned to reconcile against the next release by
 * diffing tool schemas. Two features (`knowledge_retract`, `llm_chat` usage)
 * then shipped WITHOUT a version bump, so "0.2.6" named two different tool
 * surfaces — the live daemon answered `atlas_health` with 0.2.6 while already
 * serving a tool the pinned spec had never seen. A mechanical diff would have
 * passed against the wrong surface and reported no change.
 *
 * The guard: docs/tool-schemas.json is a pure function of the registry, so any
 * added / removed / re-typed / re-described tool makes this test fail until the
 * dump is regenerated — putting the surface change and its published contract in
 * the same commit, where the version bump is impossible to miss.
 *
 * CLAIM A — the committed dump matches the live registry exactly.
 * CLAIM B — the dump's version matches package.json (the pin integrators quote).
 * CLAIM C — the dump is byte-stable: regenerating it without touching the code
 *           produces an identical file, so a non-empty diff always means a real
 *           surface change and never generation noise.
 * CLAIM D — every tool carries a name, a description and an object inputSchema,
 *           since a caller cannot construct a call from a partial entry.
 */
import * as assert from 'node:assert/strict';
import * as fs from 'node:fs';
import * as path from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildDump, serializeDump, checkDump, DUMP_PATH } from '../scripts/dump-tool-schemas.js';

const REPO_ROOT = path.resolve(path.dirname(fileURLToPath(import.meta.url)), '..');

function main(): void {
    console.log('Running tool-schema dump tests…');

    // ── CLAIM A ─────────────────────────────────────────────────────────────
    {
        const res = checkDump();
        assert.equal(
            res.ok,
            true,
            `docs/tool-schemas.json is out of date with the registry.\n` +
            `  ${res.ok ? '' : res.reason}\n` +
            `  Fix: npm run schemas:dump — and bump package.json's version if the tool surface changed.`,
        );
        console.log('  ✓ CLAIM A: committed dump matches the live tool registry');
    }

    // ── CLAIM B ─────────────────────────────────────────────────────────────
    {
        const pkg = JSON.parse(fs.readFileSync(path.join(REPO_ROOT, 'package.json'), 'utf-8')) as { version?: string };
        const dump = JSON.parse(fs.readFileSync(DUMP_PATH, 'utf-8')) as { atlasVersion?: string };
        assert.equal(dump.atlasVersion, pkg.version,
            'the published surface must be stamped with the package version an integrator pins');
        console.log(`  ✓ CLAIM B: dump is stamped ${dump.atlasVersion} — matches package.json`);
    }

    // ── CLAIM C ─────────────────────────────────────────────────────────────
    {
        const a = serializeDump(buildDump());
        const b = serializeDump(buildDump());
        assert.equal(a, b, 'dump generation must be deterministic — no timestamps or unordered keys');
        assert.equal(a, fs.readFileSync(DUMP_PATH, 'utf-8'), 'committed bytes must equal generated bytes');
        console.log('  ✓ CLAIM C: dump is byte-stable — a diff always means a real surface change');
    }

    // ── CLAIM D ─────────────────────────────────────────────────────────────
    {
        const dump = buildDump();
        assert.ok(dump.toolCount > 0, 'a dump with no tools would silently publish an empty surface');
        assert.equal(dump.tools.length, dump.toolCount, 'toolCount must describe the array it ships with');
        for (const t of dump.tools) {
            assert.ok(t.name && typeof t.name === 'string', 'every tool needs a name');
            assert.ok(t.description && typeof t.description === 'string', `tool ${t.name} has no description`);
            const schema = t.inputSchema as { type?: string } | null;
            assert.equal(schema?.type, 'object', `tool ${t.name} must declare an object inputSchema`);
        }
        // Sorted by name — the property that keeps diffs readable.
        const names = dump.tools.map((t) => t.name);
        assert.deepEqual(names, [...names].sort((a, b) => a.localeCompare(b)), 'tools must be sorted by name');
        console.log(`  ✓ CLAIM D: all ${dump.toolCount} tools are complete and name-sorted`);
    }

    console.log('tool-schema dump: all checks passed');
}

main();
